version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "portainer"
    ports:
      - 9000:9000
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PORTAINER_DATA_DIR